/** @type {import('tailwindcss').Config} */

const { fontFamily } = require('tailwindcss/defaultTheme');
const { COLORS } = require('./utilities/constants');

module.exports = {
    content: [
        './pages/**/*.{js,jsx}',
        './components/**/*.{js,jsx}',
        './lib/**/*.{js,jsx}',
    ],
    theme: {
        extend: {
            aspectRatio: {
                '4/3': '4 / 3',
            },
            colors: COLORS,
            minWidth: {
                1: '1rem',
                2: '2rem',
                3: '3rem',
                4: '4rem',
                5: '5rem',
                6: '6rem',
                7: '7rem',
                8: '8rem',
                9: '9rem',
                10: '10rem',
                11: '11rem',
                12: '12rem',
                13: '13rem',
                14: '14rem',
                15: '15rem',
                16: '16rem',
                17: '17rem',
                18: '18rem',
                19: '19rem',
                20: '20rem',
            },
        },
        fontSize: {
            xs: '.75rem',
            sm: '.875rem',
            base: '1rem',
            lg: '1.125rem',
            xl: '1.25rem',
            '2xl': '1.5rem',
            '3xl': '1.875rem',
            '4xl': '2.25rem',
            '5xl': '3rem',
            '6xl': '4rem',
            '7xl': '5rem',
            '8xl': '6rem',
            '9xl': '8rem',
            'dynamic-title': 'clamp(1.5rem, calc(1.5rem + 4cqi), 4rem)',
            'dynamic-1': 'clamp(1rem, calc(1rem + 1cqi), 3rem)',
            'dynamic-2': 'clamp(1rem, calc(1rem + 2cqi), 3rem)',
            'dynamic-3': 'clamp(1rem, calc(1rem + 2cqi), 3.5rem)',
            'dynamic-4': 'clamp(1rem, calc(1rem + 3cqi), 3.5rem)',
            'dynamic-5': 'clamp(1rem, calc(1rem + 4cqi), 3.5rem)',
            'dynamic-6': 'clamp(1rem, calc(1rem + 5cqi), 3.5rem)',
            'dynamic-7': 'clamp(1rem, calc(1rem + 6cqi), 3.5rem)',
        },
        fontFamily: {
            display: ['var(--font-playfair-display)', ...fontFamily.sans],
            sans: [
                'var(--font-raleway)',
                '-apple-system',
                'Roboto',
                'Oxygen',
                'Ubuntu',
                'Cantarell',
                'Fira Sans',
                'Droid Sans',
                'Helvetica Neue',
                'sans-serif',
                ...fontFamily.sans,
            ],
            mono: ['ui-monospace', 'SFMono-Regular'],
        },
        screens: {
            'bp-400': '400px',
            'bp-500': '500px',
            'bp-600': '600px',
            'bp-700': '700px',
            'bp-800': '800px',
            'bp-900': '900px',
            'bp-1000': '1000px',
            'bp-1100': '1100px',
            'bp-1200': '1200px',
            'bp-1400': '1400px',
            'bp-1600': '1600px',
        },
    },
    plugins: [require('@tailwindcss/container-queries')],
    content: [
        './pages/**/*.{js,jsx}',
        './components/**/*.{js,jsx}',
        './lib/**/*.{js,jsx}',
        'styles/global.css',
    ],
};
